version: 2
jobs:
 build:
   docker:
      - image: arm32v6/golang:alpine
   steps:
     - checkout

     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build -t cborum/pi-worker-server .

     - run: docker push cborum/pi-worker-server