version: 2
jobs:
 build:
   docker:
     - image: docker:latest
   steps:
     - checkout

     - setup_remote_docker:
         docker_layer_caching: true

     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build -t cborum/pi-worker-server .

     - run: docker push cborum/pi-worker-server